import React from 'react';
import { Icon } from '../ds/Icon.jsx';
import { Button } from '../ds/Button.jsx';
import { IconButton } from '../ds/IconButton.jsx';
import { Badge } from '../ds/Badge.jsx';
import { Tag } from '../ds/Tag.jsx';
import { Logo } from '../ds/Logo.jsx';
import { NeonText } from '../ds/NeonText.jsx';
import { Input } from '../ds/Input.jsx';
import { Select } from '../ds/Select.jsx';
import { Checkbox } from '../ds/Checkbox.jsx';
import { Switch } from '../ds/Switch.jsx';
import { Card } from '../ds/Card.jsx';
import { GameCard } from '../ds/GameCard.jsx';
import { ChapterCard } from '../ds/ChapterCard.jsx';
import { EventItem } from '../ds/EventItem.jsx';
import { StatCounter } from '../ds/StatCounter.jsx';
import { Tabs } from '../ds/Tabs.jsx';
import { ThemeToggle } from '../ds/ThemeToggle.jsx';
import { Dialog } from '../ds/Dialog.jsx';
import { Toast } from '../ds/Toast.jsx';
import { Tooltip } from '../ds/Tooltip.jsx';
import { Skeleton } from '../ds/Skeleton.jsx';
import { ProgressBar } from '../ds/ProgressBar.jsx';
globalThis.React = React;
globalThis.NebulaDesignSystem_8e7380 = { Icon, Button, IconButton, Badge, Tag, Logo, NeonText, Input, Select, Checkbox, Switch, Card, GameCard, ChapterCard, EventItem, StatCounter, Tabs, ThemeToggle, Dialog, Toast, Tooltip, Skeleton, ProgressBar };
